version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          parallel: true # split all specs across machines
          parallelism: 4 # use 2 CircleCI machines to finish quickly
          group: 4 machines
          post-steps:
            - store_test_results:
                path: reporters